[package]
name = "vanity-token-creator"
version = "0.1.0"
edition = "2021"
description = "a tool for creating and managing Solana vanity mints"
repository = "https://github.com/azothzephyr/vanity-token-creator"
license = "MIT"

[dependencies]
solana-sdk = "1.18.17"
solana-client = "1.18.17"
solana-program = "1.18.17"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }
clap = { version = "4.5.8", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
anyhow = "1.0.86" # for error handling
dotenv = "0.15.0" # for environment variables
spl-associated-token-account = "2.3.0"
serde_json = "1.0"

[[bin]]
name = "vanity-mint-cli"
path = "src/main.rs"